### ISSUE TITLE
Issue when there are only Alto XML files but not media (and no TSV / PDf2XML)

### ISSUE THREAD

**Issue by smachefert** [smachefert/Omeka-S-module-IiifSearch#20]
@Daniel-KM I believe there is an issue with a recent fix. I'd like to use the Alto XML files to search. I have configured ExtractOCR to create Alto XML Files only. When I run IiifSearch I get 0 results. 
The issue is that my mediaType is set to application/xml on [src/View/Helper/IiifSearch.php#L822C57-L822C61](https://github.com/smachefert/Omeka-S-module-IiifSearch/blob/bfe4ac5465d84dc68dd8b2d353080b0bc2ab4aa2/src/View/Helper/IiifSearch.php#L822C57-L822C61) but later on the mediaType is never set to alto+xml so searchFullTextAlto is not called at line 260.

Is there any reason why you didn't set the mediaType to "application/alto+xml" at line 819 ? Doing it fixes the issue in my use case, but might have side effect I don't imagine.

**Comment by smachefert** [comment]
@Daniel-KM another thing that might be related to the previous comment but now that my install has been cleaned, I see that the service is not added to the manifest. And the explanation is that in [Module.php#L63-L69](https://github.com/smachefert/Omeka-S-module-IiifSearch/blob/master/Module.php#L63-L69) the system is only doing two checks : 

- does the iiif-search/#itemid#.tsv file exists ? 
- if not, does the iiif-search/#itemid#.xml file exists ?  => is there not an issue there, can the XML file be stored in iiif-search folder, is this not only possible in pdf2xml/ ? 
- and nothing is checked for alto XML files, even if they can be used for search, no ?

I would be tempted to add after the test for the XML file (maybe changed to what I assume is the correct path of pdf2xml) the following lines : 
```php
            $simpleFilepath = $basePath . '/alto/' . $resource->id() . '.alto.xml';
            if (!file_exists($simpleFilepath)) {
                $simpleFilepath = null;
            }
```

**Comment by Daniel-KM** [comment]
Je viens de faire un pr pour cela, mais pas sûr que cela corrige tout.

**Comment by Daniel-KM** [comment]
Le 2e commit reprend la première remarque et doit corriger les problèmes.
Le fait qu'il puisse y avoir des effets de bord est significatif que le code est devenu trop complexe et qu'il faudrait le revoir.
Il y a encore des fonctionnalités à réaliser, notamment intégrer la recherche autocomplétion et intégrer la recherche via solr. Je n'ai pas cela en cours, c'est pour le futur. Si ce n'est pas fait avant, je refactoriserai à ce moment là.
